name: Build & Test Project
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link SwiftLint or install it
        run: brew link --overwrite swiftlint || brew install swiftlint || brew link --overwrite swiftlint
      - name: Install SwiftGen
        run: brew install swiftgen
      - name: Build
        run: xcodebuild -project ToDoListCleanSwift.xcodeproj -scheme ToDoListCleanSwift -destination 'platform=iOS Simulator,name=iPhone 13'
      - name: Run tests
        run: xcodebuild test -project ToDoListCleanSwift.xcodeproj -scheme ToDoListCleanSwift -destination 'platform=iOS Simulator,name=iPhone 13'
      - name: Run package's tests
        run: xcodebuild test -project ToDoListCleanSwift.xcodeproj -scheme ToDoListBusinessLogic -destination 'platform=iOS Simulator,name=iPhone 13'