name: Build & Test Project
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link SwiftLint or install it
        run: brew link --overwrite swiftlint || brew install swiftlint || brew link --overwrite swiftlint
      - name: Install SwiftGen
        run: brew install swiftgen
      - name: Build
        run: xcodebuild test -project ToDoListCleanSwift.xcodeproj -scheme ToDoListCleanSwift -destination 'platform=iOS Simulator,name=iPhone 13'
      - name: Run unit tests
        run: xcodebuild test -project ToDoListCleanSwift.xcodeproj -scheme ToDoListCleanSwiftTests -destination 'platform=iOS Simulator,name=iPhone 13'
      - name: Run UI tests
        run: xcodebuild test -project ToDoListCleanSwift.xcodeproj -scheme ToDoListCleanSwiftUITests -destination 'platform=iOS Simulator,name=iPhone 13'